services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    ports:
      - ${OLLAMA_PORT-11434}:11434

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
        BUILD_HASH: 'dev-local'
        USE_EMBEDDING_MODEL: 'sentence-transformers/all-MiniLM-L6-v2'
        USE_TIKTOKEN_ENCODING_NAME: 'cl100k_base'
        # 使用国内镜像源
        DEBIAN_MIRROR: "mirrors.tuna.tsinghua.edu.cn"
        NPM_MIRROR: "https://registry.npmmirror.com"
      dockerfile: Dockerfile.dev
    image: open-webui-dev:local
    container_name: open-webui-dev
    volumes:
      - open-webui:/app/backend/data
      # 挂载本地源码目录到容器中
      - ./backend:/app/backend
      - ./src:/app/src
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
      - 'ENV=dev'
      - 'ENABLE_RAG_HYBRID_SEARCH=false'
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}





