services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
        BUILD_HASH: 'dev-local'
      dockerfile: Dockerfile
    image: open-webui-dev:local
    container_name: open-webui-dev
    volumes:
      - open-webui:/app/backend/data
      # 挂载本地源码目录到容器中
      - ./backend:/app/backend
      - ./src:/app/src
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
      - 'ENV=dev'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}

# 开发环境构建和启动
# docker-compose -f docker-compose.dev.yaml up -d --build